USE EMPRESA;

SET GLOBAL event_scheduler = ON;

DELIMITER //
DROP EVENT IF EXISTS aumentar_presupuesto;
CREATE EVENT aumentar_presupuesto
ON SCHEDULE EVERY 6 MONTH
STARTS '2024-05-15 12:01:00'
DO
BEGIN
    UPDATE DEPARTAMENTOS
    SET Presupuesto = Presupuesto * 1.05
    WHERE Presupuesto < 20000;
END//

DELIMITER ;

SHOW EVENTS IN EMPRESA \G
