
USE ASOCIACION;

DROP TRIGGER IF EXISTS dp_borrar_socio;
CREATE TRIGGER dp_borrar_socio BEFORE DELETE ON SOCIOS
FOR EACH ROW
	INSERT INTO BAJAS_SOCIOS
	VALUES (OLD.numero, OLD.nombre,OLD.domicilio,OLD.telefono,CURDATE());
	
DELETE FROM SOCIOS WHERE nombre='Antonio Orozco';

SELECT * FROM SOCIOS;
SELECT * FROM BAJAS_SOCIOS;
