DROP DATABASE IF EXISTS RUTASCREATE DATABASE RUTAS;

USE RUTAS;

DROP TABLE IF EXISTS DISTANCIAS;
CREATE TABLE DISTANCIAS(
	ruta VARCHAR(10),
	distancia_km DECIMAL(6,2),
	distancia_milla DECIMAL(6,2),
	PRIMARY KEY (ruta)
);