/*EL PRIMER PASO E IMPRESCINDIBLE ES CREAR LA BASE DE DATOS*/

CREATE DATABASE reserva;

/*ES IMPORTANTE CREAR LAS TABLAS EN ESTE ORDEN PARA QUE NO HAYA NINGÚN PROBLEMA CON LAS CLAVES FORÁNEAS*/

CREATE TABLE ESPECIES (
    idEspecie INT PRIMARY KEY,
    NombreEspecie VARCHAR(25),
    CaracteristicasGenerales VARCHAR(250),
    PeriodoMigratorio VARCHAR(17)
);

CREATE TABLE INDIVIDUOS (
    idIndividuo INT PRIMARY KEY,
    idEspecie INT,
    Peso DECIMAL(10, 2),
    Dimensiones DECIMAL(10,2),
    FOREIGN KEY (idEspecie) REFERENCES ESPECIES(idEspecie)
);

CREATE TABLE DISPOSITIVO (
    idDispositivo INT PRIMARY KEY,
    idIndividuo INT,
    Bateria DECIMAL(5, 2),
    FOREIGN KEY (idIndividuo) REFERENCES INDIVIDUOS(idIndividuo)
);

CREATE TABLE TORRETAS (
    idTorreta INT PRIMARY KEY,
    Zona VARCHAR(25)
);
/*LA CLAVE DE ESTA TABLA PODRÍA SER UNA COMPUESTA POR idDispositivo, fecha e idTorreta, PERO POR MAYOR FACILIDAD 
HE CREADO UN CAMPO QUE SE AUTOINCREMENTE PARA GUARDAR FACILMENTE LOS REGISTROS*/
CREATE TABLE MIGRACIONES (
    idMigracion INT AUTO_INCREMENT PRIMARY KEY,
    idDispositivo INT,
    fecha DATETIME,
    esNuevo BOOLEAN,
    idTorreta INT,
    TipoMigracion ENUM('entra','sale'), 
    FOREIGN KEY (idDispositivo) REFERENCES DISPOSITIVO(idDispositivo),
    FOREIGN KEY (idTorreta) REFERENCES TORRETAS(idTorreta)
);

CREATE TABLE GRUPO_BIOLOGOS (
    idGrupo INT PRIMARY KEY,
    Provincia VARCHAR(25)
);
/*ESTA TABLA CRADA UNICAMENTE POR DOS CLAVES FORANEAS (GRUPOS y MIGRACIONES) Y UN CAMPO PARA EL TRIMESTRE ES LA QUE SIRVE DE PUENTE PARA ENVIAR LA INFORMACIÓN*/
CREATE TABLE ENVIO_INFORMACION (
    idGrupo INT,
    idMigracion INT,
    trimestre ENUM('1','2','3','4'),
    anio YEAR,
    FOREIGN KEY (idMigracion) REFERENCES MIGRACIONES(idMigracion),
    FOREIGN KEY(idGrupo) REFERENCES GRUPO_BIOLOGOS(idGrupo),
    PRIMARY KEY (idGrupo,idMigracion)
);

CREATE TABLE BIOLOGOS (
    idBiologo INT PRIMARY KEY,
    idGrupo INT,
    Nombre VARCHAR(25),
    Direccion VARCHAR(30),
    Provincia VARCHAR(25),
    FechaTitulacion DATE,
    FOREIGN KEY (idGrupo) REFERENCES GRUPO_BIOLOGOS(idGrupo)
);
