CREATE TABLE EMPLEADOS(
	dni VARCHAR(10) PRIMARY KEY,
	nombre VARCHAR(20) NOT NULL,
	apellido1 VARCHAR(15) NOT NULL,
	apellido2 VARCHAR(15) NOT NULL,
	direcc VARCHAR(25),
	ciudad VARCHAR(20),
	codPostal VARCHAR(5),
	sexo ENUM('h','n') NOT NULL,
	fecha_nac DATE
);


CREATE TABLE UNIVERSIDADES(
	univ_cod VARCHAR(5) PRIMARY KEY,
	nombre_univ VARCHAR(25),
	ciudad VARCHAR(20),
	cod_postal VARCHAR(5)
);

CREATE TABLE DEPARTAMENTOS(
	dptoCod INT AUTO_INCREMENT,
	nombre_dpto VARCHAR(30) UNIQUE NOT NULL,
	jefe VARCHAR(10),
	presupuesto DECIMAL(7,2) NOT NULL,
	PRIMARY KEY(dptoCod),
	CONSTRAINT fk_jefeD FOREIGN KEY (jefe) REFERENCES EMPLEADOS(dni) ON DELETE SET NULL
);

CREATE TABLE ESTUDIOS(
	dni_emple VARCHAR(10),
	numero INT,
	universidad VARCHAR(5),
	titulacion VARCHAR(30),
	especialidad VARCHAR(20),
	anio INT(4),
	PRIMARY KEY(dni_emple, numero),
	CONSTRAINT fk_dniempleE FOREIGN KEY(dni_emple) REFERENCES EMPLEADOS(dni) ON DELETE CASCADE,
	CONSTRAINT fk_universidadE FOREIGN KEY(universidad) REFERENCES UNIVERSIDADES(univ_cod) ON DELETE CASCADE
);

CREATE TABLE TRABAJOS(
	codigo VARCHAR(5) PRIMARY KEY,
	nombre VARCHAR(20) NOT NULL UNIQUE,
	salario DECIMAL(6,2) NOT NULL CHECK (salario <=5000) 
);

CREATE TABLE HISTORIAL_LABORAL(
	Dni_emple VARCHAR(10),
	Trabajo_cod VARCHAR(5),
	fecha_inicio DATE NOT NULL,
	fecha_fin DATE,
	PRIMARY KEY(Dni_emple, Trabajo_cod, fecha_inicio),
	CONSTRAINT fk_dniepleHL FOREIGN KEY (dni_emple) REFERENCES EMPLEADOS(dni) ON DELETE CASCADE,
	CONSTRAINT fk_trabajocodHL FOREIGN KEY (Trabajo_cod) REFERENCES TRABAJOS(codigo) ON DELETE NO ACTION
);
