# se comprueba si existe la bd, y se borra en ese caso
DROP DATABASE IF EXISTS EMPRESA;

CREATE DATABASE EMPRESA;

CREATE TABLE CENTROS (
	Numero INT PRIMARY KEY,
	Nombre VARCHAR(25) NOT NULL,
	Direccion VARCHAR(30) NOT NULL
);

SHOW CREATE TABLE CENTROS;
DESCRIBE CENTROS;

CREATE TABLE DEPARTAMENTOS (
	Numero INT PRIMARY KEY,
	Centro INT NOT NULL,
	Director INT NOT NULL,
	Tipo_dir ENUM('P','F') NOT NULL,
	Presupuesto DECIMAL(6,2) NOT NULL,
	Dpto_jefe INT NULL,
	Nombre VARCHAR(25) NOT NULL,
	CONSTRAINT fk_Centro FOREIGN KEY (Centro) REFERENCES CENTROS(Numero)
);

SHOW CREATE TABLE DEPARTAMENTOS;
DESCRIBE DEPARTAMENTOS;

CREATE TABLE EMPLEADOS (
	Cod INT PRIMARY KEY,
	Departamento INT NOT NULL,
	Telefono VARCHAR(11) NOT NULL,
	Fecha_nacimiento DATE NOT NULL,
	Fecha_ingreso DATE NOT NULL,
	Salario DECIMAL(6,2) NOT NULL,
	Comision DECIMAL(5,2) NOT NULL,
	Num_hijos INT NOT NULL,
	NOmbre VARCHAR(25),
	CONSTRAINT fk_Departamento FOREIGN KEY (Departamento) REFERENCES DEPARTAMENTOS(Numero)
);

SHOW CREATE TABLE EMPLEADOS;
DESCRIBE EMPLEADOS;

ALTER TABLE DEPARTAMENTOS ADD CONSTRAINT fk_Dpto_jefe FOREIGN KEY (Dpto_jefe) REFERENCES DEPARTAMENTOS(Numero);
ALTER TABLE DEPARTAMENTOS ADD CONSTRAINT fk_Director FOREIGN KEY (Director) REFERENCES EMPLEADOS(Cod);

SHOW CREATE TABLE DEPARTAMENTOS;
DESCRIBE DEPARTAMENTOS;

INSERT INTO CENTROS VALUES
(10, 'SEDE CENTRAL', 'C/ ALCALA 820, MADRID'),
(20, 'RELACION CON CLIENTES', 'C/ ATOCHA 405, MADRID');
	
INSERT INTO DEPARTAMENTOS VALUES
(100, 10, 260, 'P', 12, null ,'DIRECCION GENERAL');

INSERT INTO EMPLEADOS VALUES
(110, 121, 350, '1969-11-100', '1990-02-10', 1310, null, 3 ,'PONS, CESAR');

